{% set name = "sphinx-autoapi" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b5c58064214d5a846c9c81d23f00990a64654b9bca10213231db54a241bc50f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - anyascii
    - astroid >=2.7
    - jinja2
    - pyyaml
    - sphinx >=3.0
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain

test:
  requires:
    - pydocstyle
    - salvus_mesher_lite  # [osx]
  imports:
    - autoapi

about:
  home: http://github.com/rtfd/sphinx-autoapi
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.mit
  summary: Sphinx auto API documentation generator
  doc_url: http://sphinx-autoapi.readthedocs.io/en/latest/
  dev_url: https://github.com/rtfd/sphinx-autoapi

extra:
  recipe-maintainers:
    - CurtLH
